export * from "../pages/Table";
export * from "../pages/AdminDashboard";
export { default as Logout } from "../pages/auth/Logout";
export { default as CreateCategoryPage } from "../pages/admin/product/CreateCategoryPage";
export { default as CategoryListPage } from "../pages/admin/product/CategoryListPage";
export { default as CreateProductPage } from "../pages/admin/product/CreateProductPage";
export { default as ProductListPage } from "../pages/admin/product/ProductListPage";
export { default as CreatePermissionPage } from "../pages/admin/permission/CreatePermissionPage";
export { default as UserListPage } from "../pages/admin/user/UserListPage";
export { default as CreateRolePage } from "../pages/admin/role/CreateRolePage";
export { default as RoleListPage } from "../pages/admin/role/RoleListPage";
